---
baseurl: https://victor.kropp.name/
title: Victor Kropp
MetaDataFormat: yaml
DefaultContentLanguage: en
pluralizelisttitles: false
cacheDir: /home/kropp/tmp/hugo_cache/
languages:
  en:
    title: en
    weight: 1
    LanguageName: in english
    title: Victor Kropp
    copyright: Unless otherwise noted, content on this site is licensed under a <a href="http://creativecommons.org/licenses/by-nc-sa/4.0">CC BY-NC-SA 4.0</a> license. <a href="/disclaimer">Disclaimer</a>
    menu:
      main:
        - name: blog
          title: blog
          identifier: blog
          weight: 10
          url: /blog/
        - name: talks
          title: talks
          identifier: talks
          weight: 20
          url: /talks/
  ru:
    title: ru
    weight: 2
    LanguageName: по-русски
    title: Виктор Кропп
    copyright: Если не указано иного, всё содержимое сайта доступно под лицензией <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/deed.ru">CC BY-NC-SA 4.0</a>. <a href="/disclaimer">Disclaimer</a>
    menu:
      main:
        - name: на бегу
          title: на бегу
          identifier: ontherun
          weight: 10
          url: /ontherun/
#        - name: книги
#          identifier: books
#          weight: 20
#          url: /ru/books/
        - name: путешествия
          identifier: travel
          weight: 30
          url: /ru/travel/
  de:
    title: de
    weight: 3
    LanguageName: auf Deutsch
    title: Victor Kropp
    copyright: <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/deed.de">CC BY-NC-SA 4.0</a>. <a href="/disclaimer">Disclaimer</a>
---     
