---
baseurl: http://victor.kropp.name/
title: Victor Kropp
menu:
  ru:
#    - name: думаю
#      url: /ru/blog/
    - name: книги
      identifier: books
      weight: 20
      url: /ru/books/
    - name: путешествия
      identifier: travel
      weight: 30
      url: /ru/travel/
---
