---
baseurl: http://victor.kropp.name/
title: Victor Kropp
menu:
  ru:
    - name: на бегу
      title: на бегу
      identifier: ontherun
      weight: 10
      url: /ontherun/
    - name: книги
      identifier: books
      weight: 20
      url: /ru/books/
    - name: путешествия
      identifier: travel
      weight: 30
      url: /ru/travel/
---
